clinic/appointments/urls.py
from django.urls import path,include
from . import views

app_name = "appointments"

urlpatterns = [

    path('dashboard', views.dashboard , name='dashboard'),
    # path('logout' , views.logout , name='logout' ),
    path('updateProfile/<int:pk>', views.UpdateProfile , name='UpdateProfile'),
    path('createSlots/<int:pk>', views.CreateSlots , name='CreateSlots'),
    path('bookAppointment', views.BookAppointment , name='BookAppointment'),
    path('ShowAvailable', views.ShowAvailable , name='ShowAvailable'),
    path('bookSlot/<int:pk>', views.bookSlot , name='bookSlot'),
    path('cancelAppointment/<int:pk>', views.cancelAppointment , name='cancelAppointment'),
    path('deleteAppointment/<int:pk>', views.deleteAppointment , name='deleteAppointment'),
]

clinic/clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from appointments import views

urlpatterns = [
    path('' , views.homepage , name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/',include('appointments.urls')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

from django.conf.urls.static import static
from . import settings

urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

clinic/appointments/models.py
from django.contrib.auth.models import User
from users.models import CustomUser
from multiselectfield import MultiSelectField
from django.db import models
from django.shortcuts import reverse

sex = (
        ('male','male'),
        ('female','female'),
     )

blood_group = (
        ('A+','A+'),
        ('B+','B+'),
        ('AB+','AB+'),
        ('O+','O+'),
        ('A-','A-'),
        ('B-','B-'),
        ('AB-','AB-'),
        ('O-','O-'),
     )


days = (
        ('monday' , 'monday') ,
        ('tuesday' , 'tuesday') ,
        ('wednesday' , 'wednesday') ,
        ('thursday' , 'thursday') ,
        ('friday' , 'friday') ,
        ('saturday' , 'saturday') ,
        ('sunday' , 'sunday') ,
)

class Patient (models.Model):

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE , null=True)
    profile_pic = models.ImageField(upload_to='patient/', default = 'dp.png')

    name = models.CharField(max_length = 200 , blank = False)
    age = models.IntegerField(default = 18)
    sex = models.CharField(max_length = 100 , choices = sex )
    blood_group = models.CharField(max_length=10,  choices = blood_group )
    contact_no  = models.IntegerField()
    email_id = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('appointments:dashboard')
    def __str__(self):
        return self.name

class Doctor(models.Model):

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length = 200 , blank = False)
    age = models.IntegerField(default = 18)
    profile_pic = models.ImageField(upload_to='doctor/', default = 'dp.png')

    sex = models.CharField(max_length = 100 , choices = sex )
    specialization = models.CharField(max_length=100, blank = True)
    qualifications = models.CharField(max_length=100 , blank = True)
    yearsOfExperience = models.IntegerField(default = 0)
    contact_no  = models.IntegerField()
    email_id = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('appointments:dashboard')
    def __str__(self):
        return self.name

class Slot(models.Model):
    day = models.CharField(max_length = 100 ,choices = days , default='monday')
    time = models.IntegerField( blank = False)
    availability = models.IntegerField(default = 0 , blank = False)
    doctor = models.ForeignKey(Doctor , on_delete=models.CASCADE , null=True)

    def __str__(self):
        return self.doctor.name +  " " + self.day + " " + str(self.time)

class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor , on_delete=models.CASCADE , null=True)
    patient = models.ForeignKey(Patient , on_delete=models.CASCADE , null=True)
    day = models.CharField(max_length = 100 ,choices = days , default='monday')
    time = models.IntegerField( blank = False)
    cancelled = models.BooleanField( default = False)
    def __str__(self):
        return self.doctor.name +  " " + self.patient.name + " " + self.day

clinic/appointments/forms.py
from . import models
from django import forms

days = [
        ('Monday' , 'Monday') ,
        ('Tuesday' , 'Tuesday') ,
        ('Wednesday' , 'Wednesday') ,
        ('Thursday' , 'Thursday') ,
        ('Friday' , 'Friday') ,
        ('Saturday' , 'Saturday') ,
        ('Sunday' , 'Sunday') ,
]

class UpdatePatientDetail(forms.ModelForm):
    class Meta:
        model = models.Patient
        fields = [
            'name',
            'age',
            'sex',
            'blood_group',
            'contact_no',
            'email_id',
            'profile_pic'
        ]


class UpdateDoctorDetail(forms.ModelForm):
    class Meta:
        model = models.Doctor
        fields = [
            'name',
            'age',
            'sex',
            'specialization',
            'contact_no',
            'email_id',
            'qualifications',
            'yearsOfExperience',
            'profile_pic',
        ]

class BookAppointmentForm(forms.Form):
    day=forms.ChoiceField(choices=days)
    time = forms.ChoiceField(choices=[(x, x) for x in range(1, 25)])

clinic/appointments/views.py
from django.shortcuts import render
from . import models
from . import forms
from django.shortcuts import redirect , get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse

def homepage(request):
    return render(request , 'index.html')

@login_required
def dashboard(request):
    if request.user.person=='patient':
        patient = models.Patient.objects.filter(user=request.user)
        if not patient :
            form = forms.UpdatePatientDetail()
            if request.method=='POST' :
                form = forms.UpdatePatientDetail(request.POST)
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                    #we are getting an error
                return redirect('appointments:dashboard')
            else :
                return render(request,'appointments/UpdatePatientDetail.html', {'form':form , 'patient':request.user.username} )
        else:
            patient = models.Patient.objects.get(user=request.user)
            apps = models.Appointment.objects.filter(patient=patient)
            apps_new = apps.filter(cancelled=False)

            cancelled = apps.filter(cancelled=True)
            return render(request,'appointments/PatientDashboard.html',{'user':request.user , 'patient':patient, 'apps':apps_new , 'cancelled':cancelled })

    elif request.user.person=='doctor':
        doctor = models.Doctor.objects.filter(user=request.user)
        if not doctor :
            form = forms.UpdateDoctorDetail()
            if request.method=='POST' :
                form = forms.UpdateDoctorDetail(request.POST)
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                    #we are getting an error
                return redirect('appointments:dashboard')
            else :
                return render(request,'appointments/UpdateDoctorDetail.html', {'form':form , 'doctor':request.user.username} )
        else:
            doctor = models.Doctor.objects.get(user=request.user)
            apps_all = models.Appointment.objects.filter(doctor=doctor)
            apps = apps_all.filter(cancelled=False)
            # cancelled = models.Appointment.objects.filter(cancelled=True)

            return render(request,'appointments/DoctorDashboard.html',{'user':request.user , 'doctor':doctor, 'apps':apps})

def UpdateProfile(request , pk):

    if request.user.person == 'patient':
        patient = get_object_or_404(models.Patient, pk=pk)
        form = forms.UpdatePatientDetail(instance=patient)

        if request.method == 'POST':
            form = forms.UpdatePatientDetail(instance=patient, data=request.POST)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(patient.get_absolute_url())

        return render(request, 'appointments/UpdatePatientDetail.html', {'form':form, 'patient':patient})

    elif request.user.person == 'doctor':
        doctor = get_object_or_404(models.Doctor, pk=pk )
        form = forms.UpdateDoctorDetail(instance=doctor)

        if request.method == 'POST':
            form = forms.UpdateDoctorDetail(instance=doctor, data=request.POST)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(doctor.get_absolute_url())

        return render(request, 'appointments/UpdateDoctorDetail.html', {'form':form, 'doctor':doctor})


def CreateSlots(request, pk):
    if request.user.person=='doctor':
        doctor = get_object_or_404(models.Doctor, pk=pk)

        days_week = ['Monday' , 'Tuesday' , 'Wednesday', 'Thursday', 'Friday', 'Saturday']
        times = []
        working_time = [11,12,15,16,17,18]

        for i in range(1,25):
            times.append(i)

        for i in days_week:
            for j in times:
                ctr=0
                if j in working_time:
                    ctr=3
                models.Slot.objects.create(
        					day = i,
        					time = j,
        					availability = ctr,
        					doctor = doctor,
        				)

        return redirect('appointments:dashboard')
    else :
        raise HttpResponse('<h1>no access</h1>')

def BookAppointment(request):
    if request.user.person=='patient':
        form = forms.BookAppointmentForm()
        if request.method == 'POST':
            form = forms.BookAppointmentForm(request.POST)
            day = request.POST['day']
            time = int(request.POST['time'])
            if form.is_valid():
                context={'day':day, 'time':time}
                return ShowAvailable(request , context)
        else:
            return render(request, 'appointments/BookAppointment.html', {'form':form})
    else :
        raise HttpResponse('<h1>no access</h1>')


def ShowAvailable(request , context):

    day = context['day']
    time = context['time']

    all_doctors = models.Doctor.objects.all()
    context['doctors']=[]

    for i in all_doctors:

        for j in i.slot_set.all():

            if j.availability>0:
                if j.day == day and j.time == time :
                    context['doctors'].append( ( i , j ) )

    return render(request, 'appointments/ShowAvailable.html' , context)

def bookSlot(request,pk):
    slot = models.Slot.objects.get(pk=pk)
    slot.availability -= 1
    slot.save()
    patient = models.Patient.objects.get(user=request.user)
    models.Appointment.objects.create(
                day = slot.day,
                time = slot.time,
                patient = patient,
                doctor = slot.doctor,
            )

    return redirect('appointments:dashboard')


def cancelAppointment(request, pk):
    app = models.Appointment.objects.get(pk=pk)
    doctor = app.doctor
    patient = app.patient
    day = app.day
    time = app.time
    doc_slots = doctor.slot_set.all()
    doc_slots = doc_slots.filter(day=day)
    doc_slot = doc_slots.get(time=time)
    doc_slot.availability +=1
    doc_slot.save()
    app.cancelled = True
    app.save()
    return redirect('appointments:dashboard')

def deleteAppointment(request, pk):
    app = models.Appointment.objects.get(pk=pk)
    app.delete()
    return redirect('appointments:dashboard')

clinic/appointments/templates/appointments/BookAppointment.html
{% extends "base_generic.html" %}
{% load static %}

{% load crispy_forms_tags %}
{% block css %}
  <title>Data Form</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="keywords" content="Space Register Form a Responsive Web Template, Bootstrap Web Templates, Flat Web Templates, Android Compatible Web Template, Smartphone Compatible Web Template, Free Webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>

<link href="{% static 'logincss.css' %}" rel="stylesheet" type="text/css" media="all" />

<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese" rel="stylesheet">

<style>
  label{
    margin-bottom: 10px;
    margin-top: 10px;
  }

  input{
    margin-top: 10px;
  }

</style>

{% endblock %}

{% block content %}

	<div class="main">
		<div class="main-w3l">
			<h1 class="logo-w3"> </h1>
			<div class="w3layouts-main">
				<h2><span>BOOK</span></h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Search for doctors : ">
            <br>
        </form>
			</div>
		</div>
	</div>

{% endblock %}

clinic/appointments/templates/appointments/DoctorDashboard.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}

<style>

  img{
    margin-right: 15px;
  }
</style>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Patient Dashboard</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link href="{% static 'appointments/css/dashboard.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#" style="padding-top:0px;">
    <img src="{% static 'images/nll.jpg' %}" width="150" height="50" alt="Wellness">
  </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'appointments:CreateSlots' doctor.id %}">Create Slots</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'appointments:UpdateProfile' doctor.id %}">Update Profile</a>
    </li>
    <li class="nav-item" style="float:right;">
      <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
    </li>
  </ul>
</nav>

<div class="jumbotron">
  <h2>Hello Dr. {{ doctor.name }}!</h1>
</div>

{% if apps %}
<ol class="display-4">
  <li>
    {% for app in apps %}
        <div class="left-pad">
            <img class="img" src="/media/{{app.patient.profile_pic}}" height=130px width=150px>
            <div class="data"><b>Appointment</b>: {{forloop.counter}}</div>
            <div class="data"><b>Patient</b>: {{ app.patient.name }}</div>
            <div class="data"><b>Day</b>: {{ app.day }}</div>
            <div class="data"><b>Time</b>: {{ app.time }}</div>
            <!-- <form action="#">
                <input type="submit" value="Cancel Appointment">
            </form> -->
            <a href="{% url 'appointments:cancelAppointment' app.id %}"><button type="button" class="btn btn-primary btn-lg">Cancel Appointment</button></a>
            <hr align="left" width=95%>
        </div>

    {% endfor %}
  </li>
</ol>
{% else %}
<h1 class="ml-4" style="color:white;">You currently have no appointments</h1>
{% endif %}

{% endblock%}

clinic/appointments/templates/appointments/PatientDashboard.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Patient Dashboard</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link href="{% static 'appointments/css/dashboard.css' %}" rel="stylesheet" type="text/css" />
<style>
  img{
    margin-right: 10px;
  }

  .left-pad{
    padding-left: 0px;
  }
</style>
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#" style="padding-top:0px;">
    <img src="{% static 'images/nll.jpg' %}" width="150" height="50" alt="Wellness">
  </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'appointments:BookAppointment' %}">Book an appointment</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'appointments:UpdateProfile' patient.id %}">Update Profile</a>
    </li>
    <li class="nav-item" style="float:right;">
      <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
    </li>
  </ul>
</nav>

  <div class="jumbotron">
    <h2>Hello {{ patient.name }}!</h1>
  </div>
  <br>
  <h3 class="jumbotron">Booked Appointments</h1>

    {% if apps %}
    <ol class="display-4">
      <li>
        {% for app in apps %}
            <div class="left-pad">
                <img class="img" src="/media/{{app.doctor.profile_pic}}" height=130px width=150px>
                <div class="data"><b>Appointment</b>: {{forloop.counter}}</div>
                <div class="data"><b>Doctor</b>: {{ app.doctor.name }}</div>
                <div class="data"><b>Day</b>: {{ app.day }}</div>
                <div class="data"><b>Time</b>: {{ app.time }}</div>
                <!-- <form action="#">
                    <input type="submit" value="Cancel Appointment">
                </form> -->
                <a href="{% url 'appointments:cancelAppointment' app.id %}"><button type="button" class="btn btn-primary btn-lg">Cancel Appointment</button></a>
                <hr align="left" width=95%>
            </div>

        {% endfor %}
      </li>
    </ol>
    {% else %}
    <h4 style="color : white">No appointments</h1>
    {% endif %}

  <h3 class="jumbotron">Cancelled Appointments : </h1>
  {% if cancelled %}
  <ol class="display-4">
    <li>
      {% for app in cancelled %}
      <div class="left-pad">
          <img class="img" src="/media/{{app.doctor.profile_pic}}" height=130px width=150px>
          <div class="data"><b>Appointment</b>: {{forloop.counter}}</div>
          <div class="data"><b>Patient</b>: {{ app.doctor.name }}</div>
          <div class="data"><b>Day</b>: {{ app.day }}</div>
          <div class="data"><b>Time</b>: {{ app.time }}</div>
          <a href="{% url 'appointments:deleteAppointment' app.id %}"><button type="button" class="btn btn-primary btn-lg">Delete Appointment</button></a>
          <hr align="left" width=95%>
      </div>
      {% endfor %}
    </li>
  </ol>
  {% else %}
  <h4 class="ml-4" style="color : white">Hurray!! No appointments to delete</h1>
  {% endif %}

{% endblock %}

clinic/appointments/templates/appointments/ShowAvailable.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <style>body{
    margin-top:20px;
    margin-left:20px;
  }

img{

  margin-right: 20px;
}

</style>


{% endblock %}

{% block content %}
  <!-- <div class="jumbotron">
    <h1>Hello {{ request.user.name }}!</h1>
  </div> -->

  {% if doctors %}
  <h3> Here are the available doctors on {{ day }} between {{ time }} - {{ time | add:1 }} </h3>
  {% for doctor,slot in doctors %}
  <br>
  <img style = "float:left" class="img" src="/media/{{doctor.profile_pic}}" height=130px width=150px>
      <h2>{{ doctor.name }}</h2>
      <h4>{% if doctor.specialization %}{{doctor.specialization}}{% endif %}</h4>
      <a href="{% url 'appointments:bookSlot' slot.pk %}"><button>Book Now</button> </a>
      <br>
      <br>
      <br>
      <br>
      <br>
  {% endfor %}

  {% else %}
    <h3>Sorry but no doctors are available. Try changing the date and time . </h3>
    <br>
    <a href="{% url 'appointments:BookAppointment'  %}"><button type="button" class="btn btn-primary btn-lg">Try other time or date </button></a>
    <br>
    <br>
    <a href="{% url 'appointments:dashboard'  %}"><button type="button" class="btn btn-primary btn-lg">Go back to dashboard</button></a>

  {% endif %}

{% endblock%}

clinic/appointments/templates/appointments/UpdateDoctorDetail.html
{% extends "base_generic.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title%}{{doctor.name}}{% endblock %}
{% block css %}
  <title>Data Form</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="keywords" content="Space Register Form a Responsive Web Template, Bootstrap Web Templates, Flat Web Templates, Android Compatible Web Template, Smartphone Compatible Web Template, Free Webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>

<link href="{% static 'logincss.css' %}" rel="stylesheet" type="text/css" media="all" />

<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese" rel="stylesheet">

<style>
  label{
    margin-bottom: 10px;
    margin-top: 10px;
  }

  input {
  	font-weight:bold!important ;
  	text:white;
    margin-top: 10px;
  }

</style>
{% endblock %}

{% block content %}

	<div class="main">
		<div class="main-w3l">
			<h1 class="logo-w3"> </h1>
			<div class="w3layouts-main">
				<h2><span>Update Info: </span></h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit : ">
            <br>
        </form>
			</div>
		</div>
	</div>

{% endblock %}

clinic/appointments/templates/appointments/UpdatePatientDetail.html
{% extends "base_generic.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title%}{{patient.name}}{% endblock %}
{% block css %}
  <title>Data Form</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="keywords" content="Space Register Form a Responsive Web Template, Bootstrap Web Templates, Flat Web Templates, Android Compatible Web Template, Smartphone Compatible Web Template, Free Webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>

<link href="{% static 'logincss.css' %}" rel="stylesheet" type="text/css" media="all" />

<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese" rel="stylesheet">

<style>
  label{
    margin-bottom: 10px;
    margin-top: 10px;
  }

  input {
  	font-weight:bold!important ;
  	text:white;
    margin-top: 10px;
  }

</style>
{% endblock %}

{% block content %}

	<div class="main">
		<div class="main-w3l">
			<h1 class="logo-w3"> </h1>
			<div class="w3layouts-main">
				<h2><span>Personal Info: </span></h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit : ">
            <br>
        </form>
			</div>
		</div>
	</div>

{% endblock %}